[package]
name = "network"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
streams = { path = "../streams" }
tokio = { features = ["full"], version = "1.22.0" }

[lib]
name = "network"
path = "src/lib.rs"

[[bin]]
name = "networkbin"
path = "src/bin.rs"
