[package]
name = "carton"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { features = ["derive"], version = "1.0.147" }
streams = { path = "../streams" }
toml = "0.5.9"
walkdir = "2.3.2"

[lib]
name = "carton"
path = "src/lib.rs"

[[bin]]
name = "cartonbin"
path = "src/bin.rs"
